Repository makesmatheasy/makesmatheasy-documentation, pull requests merged in 2021-04, with the labels that each got.

#16 Top NavBar Added
  _includes/navbar.html
  _includes/sidebar.html
  _layouts/default.html
  public/css/style.css
  public/js/script.js
Labels: GSSOC21, Level3

#17 UI of Search bar Added Issue#13
  _includes/navbar.html
  public/css/style.css
  public/js/script.js
Labels: GSSOC21, Level1

#20 Home Button in Navbar has been fixed
  _includes/navbar.html
  index.markdown
Labels: GSSOC21, Level2

#22 feat: Change of font-size of the h1 tag
  404.html
Labels: GSSOC21, Level1

#26 Bug fixed successfully
  public/css/style.css
Labels: GSSOC21, Level0

#29 Readme file enhanced
  README.md
Labels: GSSOC21, Level3

#32 Updated navbar
  _includes/navbar.html
Labels: GSSOC21, Level2

#40 icons adjusted
  _includes/sidebar.html
  _layouts/default.html
  node_modules/.yarn-integrity
  yarn.lock
Labels: GSSOC21, Level2

#38 Dark/Light mode added
  _includes/navbar.html
  public/css/style.css
  public/js/script.js
Labels: GSSOC21, Level3

#43 Site made responsive
  about.markdown
  docs/linear_algebra.md
  public/css/style.css
Labels: GSSOC21, Level3

#48 Added Custom Scrollbar
  public/css/style.css
Labels: GSSOC21, Level2

#54 Issue 53
  _includes/navbar.html
  _includes/sidebar.html
  public/css/style.css
Labels: GSSOC21, Level3

#62 Favicon added
  _layouts/default.html
Labels: GSSOC21, Level2

#61 added probablity section
  _includes/sidebar.html
  _layouts/default.html
  docs/probablity.md
  public/images/probablity/Bayes-1.png
  public/images/probablity/Bayes-2.png
  public/images/probablity/Emprical_probablity.png
  public/images/probablity/PMF.png
  public/images/probablity/joint-probablity-venn.png
  public/images/probablity/joint.png
Labels: GSSOC21, Level3

#70 Scroll Top arrow added
  _layouts/default.html
  public/css/style.css
  public/js/script.js
Labels: GSSOC21, Level2

#69 added conic section docs
  _includes/sidebar.html
  docs/conic_section.md
  public/css/style.css
  public/gifs/conic.gif
  public/images/conic-section/circle/circle-conic.png
  public/images/conic-section/circle/circle1.png
  public/images/conic-section/circle/circle2.png
  public/images/conic-section/circle/circle3.png
  public/images/conic-section/conic-section.gif
  public/images/conic-section/ellipse-tool.png
  public/images/conic-section/ellipse/Ellipse1.png
  public/images/conic-section/ellipse/Ellipse2.png
  public/images/conic-section/ellipse/conic-sections-4.png
  public/images/conic-section/hyperbola-tool.png
  public/images/conic-section/hyperbola/Hyperbola1.png
  public/images/conic-section/hyperbola/Hyperbola2.png
  public/images/conic-section/hyperbola/hyperbola.png
  public/images/conic-section/hyperbola/hyperbola3.png
  public/images/conic-section/parabola-tool.png
  public/images/conic-section/parabola/Parabola1.png
  public/images/conic-section/parabola/Parabola2.png
  public/images/conic-section/parabola/Parabola3.png
  public/images/conic-section/parabola/Parabola4.png
  public/images/conic-section/parabola/parabola.png
  public/images/conic-section/paraboloid/Paraboloid_700.gif
  public/images/conic-section/paraboloid/paraboloid-1.png
  public/images/conic-section/paraboloid/paraboloid-2.png
Labels: GSSOC21, Level3

#72 Updated the 2D shape formulas
  docs/Graphs_and_Shapes.md
Labels: GSSOC21, Level3

#74 Sidebar updated
  _includes/sidebar.html
Labels: GSSOC21, Level2

#75 added borders to all the tabels
  docs/Graphs_and_Shapes.md
  docs/conic_section.md
  docs/general_maths.md
  docs/probablity.md
  docs/trignometry.md
Labels: GSSOC21, Level2

#77 Added article for Binary Calculations
  _includes/sidebar.html
  docs/binary_calculations.md
  public/images/1.PNG
  public/images/bin-dec.PNG
  public/images/bin-hex.PNG
  public/images/bit-cal.PNG
  public/images/excess3-dec.PNG
  public/images/grey-dec.PNG
Labels: GSSOC21, Level3

#78 fixed sidebar issue
  _config.yml
  _includes/sidebar.html
  docs/conic_section.md
  docs/probablity.md
Labels: GSSOC21, Level2

#82 updated Bed hover color in website name
  public/css/style.css
Labels: GSSOC21, Level2
