Repository makesmatheasy/makesmatheasy-documentation, pull requests merged in 2021-05, with the labels that each got.

#87 visited link css removed, changed colors of sidenav link
  docs/conversion_tools.md
  docs/general_maths.md
  public/css/style.css
Labels: GSSOC21, Level1

#91 Update README.md
  README.md
Labels: GSSOC21, Level1

#93 Added Basic Convertors Section
  docs/conversion_tools.md
  public/css/style.css
  public/images/bc1.PNG
  public/images/bc2.PNG
  public/images/bc3.PNG
  public/images/bc4.PNG
  public/images/bc5.PNG
  public/images/bc6.PNG
  public/images/bc7.PNG
  public/images/bc8.PNG
  public/images/bc9.PNG
Labels: GSSOC21, Level3

#94 Updated equations part
  docs/equations.md
  public/gifs/algeb1.gif
  public/gifs/root2.gif
Labels: GSSOC21, Level2

#99 Readme Updated
  README.md
Labels: GSSOC21, Level2

#100 Updated links to sidebar
  _includes/sidebar.html
  _layouts/default.html
  public/css/style.css
Labels: GSSOC21, Level2

#101 Fixed conic sections graphs
  _includes/sidebar.html
  docs/conic_section.md
  public/css/style.css
Labels: GSSOC21, Level2

#110 Update general maths doc
  docs/general_maths.md
  public/css/style.css
Labels: GSSOC21, Level2

#111 Update calculus doc
  docs/calculus.md
Labels: GSSOC21, Level2

#113 Sum of divisors documentation
  docs/general_maths.md
  public/images/general math/sumDiv.PNG
Labels: GSSOC21, Level3

#116 fixed internal links and social icons
  _includes/navbar.html
  _includes/sidebar.html
  _layouts/default.html
  public/css/style.css
Labels: GSSOC21, Level3

#130 added statistics section (mean,median ,mode, S.D,Weighted Mean, Sensitivity)
  _includes/sidebar.html
  docs/statistics.md
  public/images/statistics/m3-1.png
  public/images/statistics/ss-1.png
  public/images/statistics/wm-1.png
Labels: GSSOC21, Level3

#131 added T-test,AB-test,f-test,z-test,z-score calculator and negative binomial calculator
  _includes/sidebar.html
  docs/statistics.md
  public/images/statistics/ab_test.png
  public/images/statistics/f_test.png
  public/images/statistics/t_test.png
  public/images/statistics/z-score.png
  public/images/statistics/z-test.png
Labels: GSSOC21, Level3

#132 added joint,conditional,geometric probablity and relative risk calculator
  _includes/sidebar.html
  docs/probablity.md
  public/images/probablity/condi.png
  public/images/probablity/geometric.png
  public/images/probablity/relative.png
Labels: GSSOC21, Level3

#133 added Probablity docs (independent and dependent event probablity, biomial distribution and properties )
  docs/probablity.md
  public/images/probablity/independent.png
Labels: GSSOC21, Level3

#134 added Probablity docs (gamma distribution, exponential distribution, hypergeometric distribution,poission distribution )
  docs/probablity.md
  public/images/probablity/expo-dist.png
  public/images/probablity/gamma-dist.png
  public/images/probablity/pmf-geometric.png
  public/images/probablity/pmf-possion.png
Labels: GSSOC21, Level3

#137 added statistics docs for Linear Regression, covariance,correlation,margin of error ,chi-square calculators
  _includes/sidebar.html
  docs/statistics.md
  public/images/statistics/MOE.png
  public/images/statistics/chi.png
  public/images/statistics/correlaton.png
  public/images/statistics/cov.png
  public/images/statistics/linear.png
Labels: GSSOC21, Level3

#144 added docs for binary calculations
  docs/binary_calculations.md
  public/images/2421.png
  public/images/bcd.png
  public/images/compliments-2.png
  public/images/compliments.png
  public/images/hummind-distance.png
  public/images/humming-code-1.png
  public/images/humming-code-2.png
Labels: GSSOC21, Level3

#145 added addition,subtraction, multilpication and division calculators
  docs/binary_calculations.md
  public/images/addition-1.png
  public/images/addition-2.png
  public/images/divide-1.png
  public/images/divide-2.png
  public/images/multiply-1.png
  public/images/multiply-2.png
  public/images/subtract-1.png
  public/images/subtract-2.png
Labels: GSSOC21, Level3

#146 added docs for equation section (Quadratic Equation calc, intercept form of plane, and all formulas)
  docs/equations.md
  public/images/intercept.png
  public/images/quadratic-1.png
  public/images/quadratic-2.png
  public/images/quadratic-3.png
  public/images/quadratic-4.png
  public/images/quadratic-5.png
  public/images/quadratic-6.png
Labels: GSSOC21, Level3

#147 added docs for shapes section (faulhauber, congurence, similarity of triangles, percentages changes, volumetric weight calc )
  docs/Graphs_and_Shapes.md
  public/images/cs-1.png
  public/images/cs-10.jpg
  public/images/cs-11.jpg
  public/images/cs-12.jpg
  public/images/cs-2.png
  public/images/cs-3.png
  public/images/cs-4.png
  public/images/cs-5.png
  public/images/cs-6.png
  public/images/cs-7.png
  public/images/cs-8.png
  public/images/cs-9.png
  public/images/pc-cube.png
  public/images/pc-cuboid.png
  public/images/pc-vol.png
  public/images/vw-1.png
Labels: GSSOC21, Level3

#148 added docs for 2d 3d 4d shapes
  docs/Graphs_and_Shapes.md
  public/images/shapes/2d-inscribed-1.png
  public/images/shapes/2d-inscribed-2.png
  public/images/shapes/2d-inscribed-3.png
  public/images/shapes/2d-inscribed-4.png
  public/images/shapes/2d-inscribed-5.png
  public/images/shapes/2d-inscribed-6.png
  public/images/shapes/2d-inscribed-7.png
  public/images/shapes/2d-shapes-1.png
  public/images/shapes/2d-shapes-2.png
  public/images/shapes/2d-shapes-3.png
  public/images/shapes/2d-shapes-4.png
  public/images/shapes/3d-geometry-1.png
  public/images/shapes/3d-geometry-2.png
  public/images/shapes/3d-geometry-3.png
  public/images/shapes/3d-geometry-4.png
  public/images/shapes/3d-geometry-5.png
  public/images/shapes/3d-geometry-6.png
  public/images/shapes/3d-geometry-7.png
  public/images/shapes/3d-inscribed-1.png
  public/images/shapes/3d-inscribed-2.png
  public/images/shapes/3d-inscribed-3.png
  public/images/shapes/3d-inscribed-4.png
  public/images/shapes/3d-shapes-1.png
  public/images/shapes/3d-shapes-2.png
  public/images/shapes/4d-shape-1.png
  public/images/shapes/4d-shape-2.png
Labels: GSSOC21, Level3

#149 added docs for shapes section (segment, arc length, lune, cresent, platonic solids, quadlaterals)
  docs/Graphs_and_Shapes.md
  public/images/shapes/Tetrahedron.jpg
  public/images/shapes/arc-1.png
  public/images/shapes/arc.png
  public/images/shapes/crescent-1.png
  public/images/shapes/crescent-2.png
  public/images/shapes/cube.jpg
  public/images/shapes/dodoechedron.jpg
  public/images/shapes/icosahedron.jpg
  public/images/shapes/octahedron.jpg
  public/images/shapes/quad-1.png
  public/images/shapes/quad-2.png
  public/images/shapes/quad-3.png
  public/images/shapes/quadlateral.png
  public/images/shapes/segment-1.png
  public/images/shapes/segment.png
Labels: GSSOC21, Level3

#152 added docs for cartesian, spherical, polar cylindrical, coterminal, SSS triangle, parallel and striaght lines
  docs/Graphs_and_Shapes.md
  public/images/shapes/SSS.png
  public/images/shapes/cart.png
  public/images/shapes/complementary.png
  public/images/shapes/coordinate-system-1.png
  public/images/shapes/coordinate-system-2.png
  public/images/shapes/coordinate-system-3.png
  public/images/shapes/coordinate-system-4.png
  public/images/shapes/coordinate-system-5.gif
  public/images/shapes/coterminal.png
  public/images/shapes/cylinder.png
  public/images/shapes/manhattan.png
  public/images/shapes/polar.png
  public/images/shapes/spe.png
  public/images/shapes/straightline-1.png
  public/images/shapes/straightline-2.png
  public/images/shapes/straightline-3.png
  public/images/shapes/suppli.png
Labels: GSSOC21, Level3

#160 added docs for statistics
  docs/statistics.md
  public/images/statistics/confidence.png
  public/images/statistics/np-1.png
  public/images/statistics/np-2.png
  public/images/statistics/odds.png
  public/images/statistics/p-1.png
  public/images/statistics/p-2.png
  public/images/statistics/skewness.png
Labels: GSSOC21, Level3

#162 Added docs for general maths section ( pronic, automorphic, disarium, armstrong number, lucas series, smallest number divisible
  docs/general_maths.md
  public/images/general math/armstrong.png
  public/images/general math/automorphic.png
  public/images/general math/disarium.png
  public/images/general math/lucas.png
  public/images/general math/pronic.png
  public/images/general math/small.png
  public/images/general math/types-1.png
  public/images/general math/types-2.png
  public/images/general math/types-3.png
Labels: GSSOC21, Level3

#164 added docs related to general maths section ( euiler totient, permutations and combinations, co -prime number theory , polynomial degree
  docs/general_maths.md
  public/images/general math/emi.png
  public/images/general math/euler-2.png
  public/images/general math/euler.png
  public/images/general math/gst.png
  public/images/general math/prime-number.png
Labels: GSSOC21, Level3

#165 added docs related to general maths section ( golden ration, golden rectangle, hydrostatic, logorithmic, foil, binomial, pythagorean triplet
  docs/general_maths.md
  public/images/general math/binomial-1.png
  public/images/general math/binomial-2.png
  public/images/general math/foil-1.png
  public/images/general math/foil.png
  public/images/general math/golden-ratio.png
  public/images/general math/golden-rectangle.png
  public/images/general math/hydro.png
  public/images/general math/log.png
  public/images/general math/pythagorean.png
Labels: GSSOC21, Level3

#163 added docs for irichel , desargus, catalan number,double factorial, sum of divisors, sum of divisors, , smallest prime factor and next prime number
  docs/general_maths.md
  public/images/general math/catalan.png
  public/images/general math/desargues.png
  public/images/general math/divisor.png
  public/images/general math/double.png
  public/images/general math/next_prime.png
  public/images/general math/smallest_prime.png
Labels: GSSOC21, Level3

#166 added docs related to general maths section ( Euclid, antilog, doubling time, modulo, adam numbers, deciles, quartiles, exponential growth
  docs/general_maths.md
  public/images/general math/Screenshot (522).rar
  public/images/general math/ackermann.png
  public/images/general math/adam.png
  public/images/general math/antilog.png
  public/images/general math/decile.png
  public/images/general math/doubling.png
  public/images/general math/euclid.png
  public/images/general math/greatest.png
  public/images/general math/modulo.png
  public/images/general math/percentage-change.png
  public/images/general math/percentage-off.png
  public/images/general math/quartiles.png
Labels: GSSOC21, Level3

#167 added docs related to general maths section (diamond problem, additive inverse, multiplicative inverse, square root, unit rate, order of magnitude
  docs/general_maths.md
  public/images/general math/additive.png
  public/images/general math/cross.png
  public/images/general math/diamond-1.png
  public/images/general math/diamond-2.png
  public/images/general math/direct-indirect.png
  public/images/general math/expo-gro.png
  public/images/general math/half-life.png
  public/images/general math/multiplicative.png
  public/images/general math/order-of-magnitude.png
  public/images/general math/percentile.png
  public/images/general math/square-root.png
  public/images/general math/unit-calc.png
Labels: GSSOC21, Level3

#174 added docs related trignometry section (distance between incenter, excenter, curcumcenter, circum radius, area of external triangle, )
  docs/trignometry.md
  public/images/trigo/circum-radius.png
  public/images/trigo/excenter-1.png
  public/images/trigo/excenter-2.png
Labels: GSSOC21, Level3

#180 adding docs for linear algebra (mathematical reasoning, euclid geometry, sets ,realtions and functions)
  docs/linear_algebra.md
  public/images/linear/functions.png
  public/images/linear/set-1.png
  public/images/linear/set-2.png
  public/images/linear/set-3.png
  public/images/linear/set-4.png
  public/images/linear/set-5.png
  public/images/linear/set-6.png
  public/images/linear/sets.png
Labels: GSSOC21, Level3

#170 added docs related to general maths section (hyperperfect,exponents,clock angle, root mean,nth base, squares and cubes, woodall, wagstaff, kaprekar)
  docs/general_maths.md
  public/images/general math/abundant.png
  public/images/general math/clock-angle-1.png
  public/images/general math/clock-angle-2.png
  public/images/general math/exponents_solve.png
  public/images/general math/hyperperfect.png
  public/images/general math/kapreakar.png
  public/images/general math/nn-1.png
  public/images/general math/nn-2.png
  public/images/general math/nn-3.png
  public/images/general math/nn-4.png
  public/images/general math/nn-5.png
  public/images/general math/nn-6.png
  public/images/general math/nn-7.png
  public/images/general math/nth-base-calc.png
  public/images/general math/root-mean-square.png
  public/images/general math/square_sum.png
  public/images/general math/wagstaff.png
  public/images/general math/woodall.png
  public/images/general math/work-time.png
Labels: GSSOC21, Level3

#173 added docs related to general maths section (perfect squeares, cubes in a range, factorization, error percentage, intrest rate, selling price and cost price,profit loss, and set calculator)
  docs/general_maths.md
  public/images/general math/cost-selling.png
  public/images/general math/effective-intrest.png
  public/images/general math/factor - 2.png
  public/images/general math/factor -1.png
  public/images/general math/percentage-1.png
  public/images/general math/percentage-2.png
  public/images/general math/percentage-3.png
  public/images/general math/perfect-square-1.png
  public/images/general math/perfect-square-2.png
  public/images/general math/set-calc.png
Labels: GSSOC21, Level3

#175 added docs related trignometry section (sum , difference of trignometric functions, expansions of functions , height , distance and unit circle )
  docs/trignometry.md
  public/images/trigo/hd-1.png
  public/images/trigo/hd-2.png
  public/images/trigo/hd-3.png
  public/images/trigo/hd-4.png
  public/images/trigo/hd-5.png
  public/images/trigo/sol-1.png
  public/images/trigo/sol-2.png
  public/images/trigo/sol-3.png
  public/images/trigo/sol-4.png
  public/images/trigo/sum-diff.png
  public/images/trigo/unit-circle.png
Labels: GSSOC21, Level3

#181 added docs related docs for linear algebra section (sets formulas, sigma notations, cramers rule, and properties)
  docs/linear_algebra.md
  public/images/cramer-1.png
  public/images/cramer-2.png
Labels: GSSOC21, Level3

#183 added docs related to linear algrbra (Ap,GP,HP,Aliquot Sums, Golden and Silver Ratio )
  docs/linear_algebra.md
  public/images/util/al-1.png
  public/images/util/al-2.png
  public/images/util/gs-1.png
  public/images/util/gs-2.png
  public/images/util/sn-1.png
  public/images/util/sn-2.png
  public/images/util/sn-3.png
  public/images/util/sn-4.png
  public/images/util/sn-5.png
  public/images/util/sn-6.png
Labels: GSSOC21, Level3

#182 added docs related to linear algebra section (cayley hamilton theorem, mean calculator, sequence and series)
  docs/linear_algebra.md
  public/images/meanc-1.png
  public/images/meanc-2.png
  public/images/meanc-3.png
  public/images/meanc-4.png
Labels: GSSOC21, Level3

#188 fixed typos and errors in Linear Algebra Section , Conic Section , trignometry and Calculus section
  docs/calculus.md
  docs/linear_algebra.md
  docs/trignometry.md
  public/images/trigo/excenter-1.png
  public/images/trigo/excenter-2.png
  public/images/trigo/hd-1.png
  public/images/trigo/hd-2.png
  public/images/trigo/hd-3.png
  public/images/trigo/hd-4.png
  public/images/trigo/hd-5.png
  public/images/trigo/sol-1.png
  public/images/trigo/sol-2.png
  public/images/trigo/sol-3.png
  public/images/trigo/sol-4.png
  public/images/trigo/sum-diff.png
Labels: GSSOC21, Level3

#189 fixed errors in general maths, equations, graphs and shapes, conversion tool section
  docs/Graphs_and_Shapes.md
  docs/equations.md
  docs/general_maths.md
Labels: GSSOC21, Level2

#190 fixed errors in complex numbers, binary calculations, statistics and probablity sections
  docs/binary_calculations.md
  docs/probablity.md
  docs/statistics.md
Labels: GSSOC21, Level2
